# -*- coding: utf-8 -*-
"""gpt-augmentor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6s1pTq0pQcUH2tgpXHb6AVamtg5-hTi
"""

import csv
import openai
import pandas as pd
import time
import os

# Set your OpenAI API key
openai.api_key = 'your openAI API key'

def paraphrase_text(text):
    response =  openai.ChatCompletion.create(
        model = 'gpt-3.5-turbo',
        messages = [
            {"role": "system", "content" : "You are a helpful assistant."},
            {"role": "user", "content" : f"Please paraphrase: {text}"}
        ],
        temperature=0.3,  # Higher value: more random, lower value: more deterministic
        max_tokens=300, # Adjust as needed
        timeout=1200  # Timeout in seconds
    )
    print(response)
    return response['choices'][0]['message']['content'].strip()


def paraphrase_csv(input_file, output_file):
    df = pd.read_csv(input_file)

    # Creating or loading an output DataFrame
    if os.path.isfile(output_file):
        paraphrased_df = pd.read_csv(output_file)
    else:
        paraphrased_df = pd.DataFrame(columns=['Question', 'Answer'])

    start = len(paraphrased_df)

    for index, row in df[start:].iterrows():
        print(f"Paraphrasing row {index+1}...")
        question = paraphrase_text(row['Question'])
        time.sleep(50)
        answer = paraphrase_text(row['Answer'])

        # Append the new row to the DataFrame and save it to the CSV file
        new_row = {'Question': question, 'Answer': answer}
        paraphrased_df = paraphrased_df.append(new_row, ignore_index=True)
        paraphrased_df.to_csv(output_file, index=False)


# Call the function
paraphrase_csv('path_of_the_file_that_will_be_augmented', 'output_file.csv')

